[package]
name = "kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc", features = ["serde"] }
memmap2 = "0.9.0"
serde = "1.0.192"
thiserror = "1.0.50"
